spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: flyzz
    password: 20010121
    url: jdbc:mysql://127.0.0.1:3306/flash_sale?characterEncoding=utf8&serverTimezone=UTC&&rewriteBatchedStatements=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      filters: stat
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    lettuce:
      pool:
        enabled: true
        min-idle: 5
        max-active: 20
        max-idle: 10
    host: 127.0.0.1
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  tomcat:
    accept-count: 800
    threads:
      max: 800
      min-spare: 100
